version: '3'



services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # NEXT BUILD REQUIRES THESE AT BUILD TIME
        PAYLOAD_SECRET: ${PAYLOAD_SECRET}
        DATABASE_URI: ${DATABASE_URI:-mongodb://mongo:27017/wotan}

        # Next-only public envs (safe for build)
        NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
        PAYLOAD_PUBLIC_SERVER_URL: ${PAYLOAD_PUBLIC_SERVER_URL}

        # SMTP config (needed during build when Payload initializes)
        SMTP_EMAIL: ${SMTP_EMAIL}
        SMTP_HOST: ${SMTP_HOST}
        SMTP_USER: ${SMTP_USER}
        SMTP_PASS: ${SMTP_PASS}
        SMTP_PORT: ${SMTP_PORT}

    image: wotan-website:latest

    env_file:
      - .env

    environment:
      NODE_ENV: production
      DATABASE_URI: ${DATABASE_URI:-mongodb://mongo:27017/wotan}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      PAYLOAD_CONFIG_PATH: dist/payload/payload.config.js
      PAYLOAD_PUBLIC_SERVER_URL: ${PAYLOAD_PUBLIC_SERVER_URL}
      NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
      SMTP_EMAIL: ${SMTP_EMAIL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_PORT: ${SMTP_PORT}

    depends_on:
      - mongo

    expose:
      - "3000"

    volumes:
      - media:/home/node/app/media

    networks:
      - app_network
      - web

    restart: unless-stopped


  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
      - --bind_ip_all
    volumes:
      - data:/data/db
    logging:
      driver: none
    networks:
      - app_network
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/sites:/etc/nginx/conf.d:ro
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    depends_on:
      - payload
    networks:
      - web
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: ""
    command: sleep infinity
    networks:
      - web  


volumes:
  data:
  media:

networks:
  app_network:
    driver: bridge
  web:
    driver: bridge
