version: '3'



services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # NEXT BUILD REQUIRES THESE AT BUILD TIME
        PAYLOAD_SECRET: ${PAYLOAD_SECRET}
        DATABASE_URI: ${DATABASE_URI:-mongodb://mongo:27017/wotan}

        # Next-only public envs (safe for build)
        NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
        PAYLOAD_PUBLIC_SERVER_URL: ${PAYLOAD_PUBLIC_SERVER_URL}

    image: wotan-website:latest

    env_file:
      - .env

    environment:
      NODE_ENV: production
      DATABASE_URI: ${DATABASE_URI:-mongodb://mongo:27017/wotan}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      PAYLOAD_CONFIG_PATH: dist/payload/payload.config.js

    depends_on:
      - mongo

    ports:
      - "3000:3000"

    networks:
      - app_network

    restart: unless-stopped


  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
      - --bind_ip_all
    volumes:
      - data:/data/db
    logging:
      driver: none
    networks:
      - app_network
    restart: unless-stopped


volumes:
  data:

networks:
  app_network:
    driver: bridge
