version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn build && yarn serve"
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - app_network

  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
      - --bind_ip_all
    volumes:
      - data:/data/db
      - ./dump:/dump
    logging:
      driver: none
    networks:
      - app_network

volumes:
  data:
  node_modules:

networks:
  app_network:
    driver: bridge
