import {
  X,
  Eye,
  File,
  Save,
  Trash,
  Heart,
  Video,
  Shirt,
  Upload,
  Search,
  SearchX,
  Printer,
  Calendar,
  ArrowLeft,
  UserRound,
  FileImage,
  SquarePen,
  PhoneCall,
  ArrowRight,
  PlusCircle,
  CheckCircle,
  ShoppingCart,
  ChevronsDown,
  AudioWaveform,
  FolderArchive,
  AlertTriangle,
  MoreHorizontal,
  LinkIcon,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Gem,
  Rocket,
  MapPin,
  Phone,
  Mail,
  Send,
  Plus,
  Minus,
  MoveRight,
  ChevronsUpDown,
  Loader2,
  Download,
  Copy,
} from 'lucide-react'

export const Icons = {
  Close: X,
  Look: Eye,
  Mail: Mail,
  Plus: Plus,
  Save: Save,
  File: File,
  Pin: MapPin,
  Values: Gem,
  Trash: Trash,
  Video: Video,
  Shirt: Shirt,
  Minus: Minus,
  Message: Send,
  Upload: Upload,
  Search: Search,
  Print: Printer,
  Add: PlusCircle,
  Edit: SquarePen,
  User: UserRound,
  Mission: Rocket,
  Favorite: Heart,
  Phone: PhoneCall,
  Anchor: LinkIcon,
  Cart: ShoppingCart,
  Check: CheckCircle,
  Calendar: Calendar,
  SearchFail: SearchX,
  Dots: MoreHorizontal,
  ArrowLeft: ArrowLeft,
  FileImage: FileImage,
  ArrowRight: ArrowRight,
  Warning: AlertTriangle,
  ChevronDown: ChevronDown,
  ChevronLeft: ChevronLeft,
  LongArrowRight: MoveRight,
  ChevronRight: ChevronRight,
  ChevronsDown: ChevronsDown,
  AudioWaveform: AudioWaveform,
  FolderArchive: FolderArchive,
  ChevronsUpDown: ChevronsUpDown,
  Loader: Loader2,
  Download: Download,
  Copy: Copy,
}
